ADLF/Controllers/CategoriaAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADLF.Models;
using ADLF.Repositories;

namespace ADLF.Controllers
{
    public class CategoriaAdsController : Controller
    {
        private ICategoriasRepository categoriasRepository;


        public CategoriaAdsController(ICategoriasRepository categoriasRepository)
        {
            this.categoriasRepository = categoriasRepository;
        }

        // GET: CategoriaAds
        public async Task<IActionResult> Index()
        {
            var addslist = await categoriasRepository.GetAll();
            return View(addslist);
        }

        // GET: CategoriaAds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            
            var categoriaAd = await categoriasRepository.GetById(id.Value);
            if (categoriaAd == null)
            {
                return NotFound();
            }

            return View(categoriaAd);
        }

        // GET: CategoriaAds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CategoriaAds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTipoad,CategoriaName")] CategoriaAd categoriaAd)
        {
            if (ModelState.IsValid)
            {
                categoriaAd = await categoriasRepository.Insert(categoriaAd);
                var id = categoriaAd.IdTipoad;

                return RedirectToAction(nameof(Index));
            }
            return View(categoriaAd);
        }

        // GET: CategoriaAds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaAd = await categoriasRepository.GetById(id.Value);
            if (categoriaAd == null)
            {
                return NotFound();
            }
            return View(categoriaAd);
        }

        // POST: CategoriaAds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTipoad,CategoriaName")] CategoriaAd categoriaAd, string catename, int? idcate)
        {
            if (idcate == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                categoriaAd = await categoriasRepository.Update(categoriaAd, catename, idcate);
                return RedirectToAction(nameof(Index));
            }
            return View(categoriaAd);
        }

        // GET: CategoriaAds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoriaAd = await categoriasRepository.GetById(id.Value);
            if (categoriaAd == null)
            {
                return NotFound();
            }

            return View(categoriaAd);
        }

        // POST: CategoriaAds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await categoriasRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        
    }
}

ADLF/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="ThemeStarz">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.css" type="text/css">
    <link href="~/assets/bootstrap/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/assets/bootstrap/css/bootstrap-reboot.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/selectize.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/user.css">
    <link href="~/assets/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/assets/css/user.css" rel="stylesheet" />
    <link href="~/assets/fonts/font-awesome.css" rel="stylesheet" />

    <title>Ads by Lui</title>

</head>

<body>
    <div class="page sub-page">
        <!--*********************************************************************************************************-->
        <!--************ HERO ***************************************************************************************-->
        <!--*********************************************************************************************************-->
        <section class="hero">
            <div class="hero-wrapper">
                <!--============ Secondary Navigation ===============================================================-->
                <div class="secondary-navigation">
                    <div class="container">
                        <ul class="left">
                            <li>
                                <span>
                                    @*<i class="fa fa-phone"></i>*@
                                </span>
                            </li>
                        </ul>
                        <!--end left-->
                        
                        <ul class="right">
                            <li>
                                @*<a href="my-ads.html">
                <i class="fa fa-heart"></i>My Ads
            </a>*@
                            </li>
                            @if (Context.Session.GetString("usuariodata") != null)
                            {
                                <li>
                                    <a href="#">
                                        <i class="fa fa-user-md"></i> @Context.Session.GetString("usuariodata")


                                    </a>


                                </li>

                                <li>
                                    <form method="post" enctype="multipart/form-data" action="/Users/Desconectarse">
                                        <input type="submit" class="btn btn-secondary small " style="background:none;" value="Desconectarse" />

                                    </form>
                                </li>

                            }
                            else
                            {
                                <li>
                                    <a href="@Url.Action("Login","Home")">
                                        <i class="fa fa-sign-in"></i>Iniciar Sesion
                                    </a>
                                </li>
                                <li>

                                    <a href="@Url.Action("Registrar","Home")">
                                        <i class="fa fa-user-plus"></i>Registrar
                                    </a>
                                </li>
                            }




                        </ul>
                      
                            <!--end right-->
                    </div>
                    <!--end container-->
                </div>
                <!--============ End Secondary Navigation ===========================================================-->
                <!--============ Main Navigation ====================================================================-->
                <div class="main-navigation">
                    <div class="container">
                        <nav class="navbar navbar-expand-lg navbar-light justify-content-between">
                            <a class="navbar-brand" href="@Url.Action("Index","Anuncios")">
                                <img src="~/assets/img/logobylui.png" alt="">
                            </a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbar">
                                <!--Main navigation list-->
                                <ul class="navbar-nav">
                                    <li class="nav-item active has-child">
                                        <a class="nav-link" href="@Url.Action("Index","Anuncios")">Anuncios</a>
                                        <ul class="child">
                                            <li class="nav-item">
                                                <a href="@Url.Action("AdDestacados","Anuncios")" class="nav-link">Destacados</a>
                                            </li>
                                            
                                        </ul>
                                    </li>
                                
                                   
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("Index","CategoriaAds")">Categorias</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("Create","Anuncios")" class="btn btn-primary text-caps btn-rounded btn-framed">Crear Anuncio</a>
                                    </li>
                                </ul>
                                <!--Main navigation list-->
                            </div>
                            <!--end navbar-collapse-->
                            @*<a href="#collapseMainSearchForm" class="main-search-form-toggle" data-toggle="collapse" aria-expanded="false" aria-controls="collapseMainSearchForm">
                                <i class="fa fa-search"></i>
                                <i class="fa fa-close"></i>
                            </a>*@
                            <!--end main-search-form-toggle-->
                        </nav>
                        <!--end navbar-->
                        @*<ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Library</a></li>
                            <li class="breadcrumb-item active">Data</li>
                        </ol>*@
                        <!--end breadcrumb-->
                    </div>
                    <!--end container-->
                </div>
                <!--============ End Main Navigation ================================================================-->
                <!--============ Hero Form ==========================================================================-->
                
                <!--end collapse-->
                <!--============ End Hero Form ======================================================================-->
                <!--============ Page Title =========================================================================-->
                <div class="page-title">
                    <div class="container">
                        <h1><a class="text-secondary" href="@Url.Action("Index","Anuncios")" >App Anuncios</a> </h1>
                    </div>
                    <!--end container-->
                </div>
                <!--============ End Page Title =====================================================================-->
                <div class="background"></div>
                <!--end background-->
            </div>
            <!--end hero-wrapper-->
        </section>
        <!--end hero-->
        <!--*********************************************************************************************************-->
        <!--************ CONTENT ************************************************************************************-->

        @RenderBody()
        <!--*********************************************************************************************************-->
        <!--end content-->
        <!--*********************************************************************************************************-->
        <!--************ FOOTER *************************************************************************************-->
        <!--*********************************************************************************************************-->
       
        <!--end footer-->
    </div>
    <!--end page-->

    <script type="~/text/javascript" src="~/assets/js/infobox.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jquery-validate.bootstrap-tooltip.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jQuery.MultiFile.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jquery.nouislider.all.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/map.js"></script>
    <script type="~/text/javascript" src="~/assets/js/markerclusterer_packed.js"></script>
    <script type="~/text/javascript" src="~/assets/js/owl.carousel.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/readmore.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/richmarker-compiled.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jquery-3.3.1.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/popper.min.js"></script>
    <script type="~/text/javascript" src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="~/text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyBEDfNcQRmKQEyulDN8nGWjLYPm8s4YB58&libraries=places"></script>
    <script type="~/text/javascript" src="~/assets/js/selectize.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/masonry.pkgd.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/icheck.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/jquery.validate.min.js"></script>
    <script type="~/text/javascript" src="~/assets/js/custom.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>